# Generated by Django 5.2.7 on 2025-11-03 12:34

import apps.deployedapps.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedApp',
            fields=[
                ('id', models.CharField(default=apps.deployedapps.models.generate_app_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='users.user')),
            ],
            options={
                'db_table': 'deployed_apps',
                'ordering': ['-created_at'],
            },
        ),
    ]
