# Generated by Django 5.2.7 on 2025-11-03 12:34

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=apps.users.models.generate_user_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('plan', models.CharField(choices=[('HOBBY', 'Hobby'), ('PRO', 'Pro')], default='HOBBY', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
